FROM node:16 as build

WORKDIR /app

COPY ./client /app
COPY ./shared /shared

RUN npm ci
RUN npm run build:staging

FROM caddy:2-alpine

WORKDIR /app
COPY --from=build /app/dist /app/dist
COPY ./client/Caddyfile.staging /etc/caddy/Caddyfile
