version: '3.7'

services:
  server: 
    restart: unless-stopped
    image: fkropfhamer/generic_game_server
    build: 
      context: .
      target: app_server

  client:
    restart: unless-stopped
    image: fkropfhamer/generic_game_client
    build:
      context: .
      target: app_client
    volumes:
      - type: volume
        source: caddy_data
        target: /data
      - type: volume
        source: caddy_config
        target: /config
    ports:
      - target: 80
        published: 80
        protocol: tcp
      - target: 443
        published: 443
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost:80}

volumes:
  caddy_data:
  caddy_config:
